#!/bin/bash
# Shardbyte MOTD

USER=$(whoami)
HOSTNAME=$(uname -n)
IP=$(hostname -I)
HOME=$(df -Ph | grep home | awk '{print $4}' | tr -d '\n')
NUM_UNIQUE_USERS=$(users | tr ' ' '\n' | sort | uniq | wc -w)
MEMORY=$(free -m | grep "Mem" | awk '{print $2,"-",$3,"-",$4}')
SWAP=$(free -m | grep "Swap" | awk '{print $2,"-",$3,"-",$4}')
PSA=$(ps -Afl | wc -l)


# Time of day
HOUR=$(date +"%H")
if [ "$HOUR" -lt 12 ]; then
    TIME="morning"
elif [ "$HOUR" -lt 17 ]; then
    TIME="afternoon"
else
    TIME="evening"
fi

# System uptime
uptime_seconds=$(cut -f1 -d. /proc/uptime)
upDays=$((uptime_seconds / 60 / 60 / 24))
upHours=$((uptime_seconds / 60 / 60 % 24))
upMins=$((uptime_seconds / 60 % 60))
upSecs=$((uptime_seconds % 60))

#System load
read -r LOAD1 LOAD5 LOAD15 < /proc/loadavg

# Define color variables
COLOR_COLUMN="\e[1m-"    # Bold text and a hyphen
COLOR_VALUE="\033[38;5;69;48;5;234m"     # Blueish Purple text
RESET_COLORS="\e[0m"     # Reset colors to default

echo ""
echo -e "\e[7m--- GOOD $TIME $USER ----\e[0m"
echo ""
MESSAGE=$(/usr/bin/neofetch)
echo -e " $MESSAGE"
RULES="$RESET_COLORS\033[38;5;215;48;5;234m
  ::::::::::::::::::::::::::::::::::-RULES-::::::::::::::::::::::::::::::::::
    This is a private system that you are not to give out access to anyone   
   without permission from the admin. Keep it OS (OldSkool) and Stay Frosty. 
                   -==  THE SHARDBYTE COLLECTIVE  ==-$RESET_COLORS"
echo -e " $RULES"


echo -e "

 $COLOR_COLUMN- Hostname$RESET_COLORS............: $COLOR_VALUE $HOSTNAME $RESET_COLORS
 $COLOR_COLUMN- IP Address$RESET_COLORS..........: $COLOR_VALUE $IP $RESET_COLORS
 $COLOR_COLUMN- Release$RESET_COLORS.............: $COLOR_VALUE $(cat /etc/redhat-release) $RESET_COLORS
 $COLOR_COLUMN- Users$RESET_COLORS...............: $COLOR_VALUE Currently $NUM_UNIQUE_USERS DIFFERENT user(s) logged on $RESET_COLORS
 $COLOR_COLUMN- Current user$RESET_COLORS........: $COLOR_VALUE $USER $RESET_COLORS
 $COLOR_COLUMN- CPU usage$RESET_COLORS...........: $COLOR_VALUE $LOAD1 - $LOAD5 - $LOAD15 (1-5-15 min) $RESET_COLORS
 $COLOR_COLUMN- Memory used$RESET_COLORS.........: $COLOR_VALUE $MEMORY (total-free-used) $RESET_COLORS
 $COLOR_COLUMN- Swap in use$RESET_COLORS.........: $COLOR_VALUE $SWAP (total-used-free) MB $RESET_COLORS
 $COLOR_COLUMN- Processes$RESET_COLORS...........: $COLOR_VALUE $PSA running $RESET_COLORS
 $COLOR_COLUMN- System uptime$RESET_COLORS.......: $COLOR_VALUE $upDays days $upHours hours $upMins minutes $upSecs seconds $RESET_COLORS
 $COLOR_COLUMN- Disk space HOME$RESET_COLORS.....: $COLOR_VALUE $HOME remaining $RESET_COLORS
"
