#!/bin/bash
###########################
#                         #
#  Saint @ Shardbyte.com  #
#                         #
###########################
######  BEGIN FILE  ###### ######  BEGIN FILE  ###### ######  BEGIN FILE  ######
# Dynamic MOTD
#
#
USER=$(whoami)
HOSTNAME=$(uname -n)
OS_NAME=$(grep -oP 'PRETTY_NAME="\K[^"]+' /etc/os-release)
IP=$(hostname -I)
HOME=$(df -Ph | grep home | awk '{print $4}' | tr -d '\n')
PSA=$(ps -Afl | wc -l)

# Time of day
HOUR=$(date +"%H")
if [ "$HOUR" -lt 12 ]; then
    TIME="morning"
elif [ "$HOUR" -lt 17 ]; then
    TIME="afternoon"
else
    TIME="evening"
fi

# System uptime
uptime_seconds=$(cut -f1 -d. /proc/uptime)
upDays=$((uptime_seconds / 60 / 60 / 24))
upHours=$((uptime_seconds / 60 / 60 % 24))
upMins=$((uptime_seconds / 60 % 60))
upSecs=$((uptime_seconds % 60))

# Define color variables
COLOR_COLUMN="\e[1m-"                    # Bold text and a hyphen
COLOR_VALUE="\033[38;5;69;48;5;234m"     # Blueish Purple text
RESET_COLORS="\e[0m"                     # Reset colors to default
#######################################################
# USER VIEW
#######################################################

echo ""
echo -e "\e[7m--- GOOD $TIME $USER ----\e[0m"
echo ""
MESSAGE=$(/usr/bin/neofetch)
echo -e " $MESSAGE"
RULES="$RESET_COLORS\033[38;5;215;48;5;234m
  ::::::::::::::::::::::::::::::::::-RULES-::::::::::::::::::::::::::::::::::
    This is a private system that you are not to give out access to anyone   
   without permission from the admin. Keep it OS (OldSkool) and Stay Frosty. 
                   -==  THE SHARDBYTE COLLECTIVE  ==- $RESET_COLORS"
echo -e " $RULES"

